# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "85c0b7c4d7c4271b231a63f20907f6d7"
name = "Apex Remix"
handle = "apex-remix"
application_url = "https://apex-invoice-remix.appforge.ca"
embedded = true

[build]
dev_store_url = "app-forge.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_metaobject_definitions,read_metaobjects,read_orders,write_products"

[auth]
redirect_urls = [
  "https://apex-invoice-remix.appforge.ca/auth/callback",
  "https://apex-invoice-remix.appforge.ca/auth/shopify/callback",
  "https://apex-invoice-remix.appforge.ca/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
